---
- hosts: dockers
  become: true
  vars_files:
    - "vars/docker.yml"
    - "vars/common.yml"
  vars: []

  roles:
    - { role: bt11.base }

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      when: "ansible_os_family == 'Debian'"

    - name: upgrade all packages
      become: true
      yum:
        name: '*'
        state: latest
      when: "ansible_os_family == 'RedHat'"
