---
- hosts: dockers
  become: true
  vars_files:
    - "vars/docker.yml"
    - "vars/common.yml"
  vars:
    install_updates_now: true

  roles:
    - { role: bt11.base }

  tasks:
    - name: Update and upgrade apt packages
      become: true
      command: apt-get upgrade -y -o Dir::Etc::SourceList=/etc/apt/security.sources.list
      when:
        - "ansible_os_family == 'Debian'"
        - install_updates_now

    - name: upgrade all packages
      become: true
      yum:
        name: '*'
        state: latest
      when:
        - "ansible_os_family == 'RedHat'"
        - install_updates_now
