galaxy_info:
  author: your name
  description: your description
  company: your company (optional)
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  galaxy_tags: []

dependencies:
  - { role: mstefany.auditd, when: ansible_os_family == 'RedHat' }
  - { role: dev-sec.os-hardening }
  - { role: dev-sec.ssh-hardening }
  - { role: tschifftner.autoupdate, when: ansible_os_family == 'Debian'}
